import '../models/alphabet_en_model.dart';

List<alphabetEnModel> LatinAlphabetEnList = [
  alphabetEnModel(text: 'a', audio: 'assets/audio/kid-a.mp3'),
  alphabetEnModel(text: 'b', audio: 'assets/audio/kid-b.mp3'),
  alphabetEnModel(text: 'c', audio: 'assets/audio/kid-c.mp3'),
  alphabetEnModel(text: 'd', audio: 'assets/audio/kid-d.mp3'),
  alphabetEnModel(text: 'e', audio: 'assets/audio/kid-e.mp3'),
  alphabetEnModel(text: 'f', audio: 'assets/audio/kid-f.mp3'),
  alphabetEnModel(text: 'g', audio: 'assets/audio/kid-g.mp3'),
  alphabetEnModel(text: 'h', audio: 'assets/audio/kid-h.mp3'),
  alphabetEnModel(text: 'i', audio: 'assets/audio/kid-i.mp3'),
  alphabetEnModel(text: 'j', audio: 'assets/audio/kid-j.mp3'),
  alphabetEnModel(text: 'k', audio: 'assets/audio/kid-k.mp3'),
  alphabetEnModel(text: 'l', audio: 'assets/audio/kid-l.mp3'),
  alphabetEnModel(text: 'm', audio: 'assets/audio/kid-m.mp3'),
  alphabetEnModel(text: 'n', audio: 'assets/audio/kid-n.mp3'),
  alphabetEnModel(text: 'o', audio: 'assets/audio/kid-o.mp3'),
  alphabetEnModel(text: 'p', audio: 'assets/audio/kid-p.mp3'),
  alphabetEnModel(text: 'q', audio: 'assets/audio/kid-q.mp3'),
  alphabetEnModel(text: 'r', audio: 'assets/audio/kid-r.mp3'),
  alphabetEnModel(text: 's', audio: 'assets/audio/kid-s.mp3'),
  alphabetEnModel(text: 't', audio: 'assets/audio/kid-t.mp3'),
  alphabetEnModel(text: 'u', audio: 'assets/audio/kid-u.mp3'),
  alphabetEnModel(text: 'v', audio: 'assets/audio/kid-v.mp3'),
  alphabetEnModel(text: 'w', audio: 'assets/audio/kid-w.mp3'),
  alphabetEnModel(text: 'x', audio: 'assets/audio/kid-x.mp3'),
  alphabetEnModel(text: 'y', audio: 'assets/audio/kid-y.mp3'),
  alphabetEnModel(text: 'z', audio: 'assets/audio/kid-z.mp3')
];
